import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import AdminLayout from "@/components/layouts/AdminLayout";
import ReduxProvider from "@/components/providers/ReduxProvider";
import SessionSync from "@/components/providers/SessionSync";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AdminRootLayout({
    children,
}) {
    return (
        <ReduxProvider>
            <SessionSync />
            <AdminLayout>
                {children}
            </AdminLayout>
        </ReduxProvider>
    );
}
